name: 'Pogbot: Generate BuildData'

on:
  pull_request:
  push:
    paths-ignore:
      - 'build.json'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 'Git: Checkout'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: "Node: Setup"
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: 'Node: Generate build data'
        id: script
        run: npm run prestart
      - name: 'Git: Send them back'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: Builder John 👷‍♂️
          commit_message: 'ci: generate builddata'
