name: "Pogbot: Generate BuildData"

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: "Git: Checkout"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: "Node: Setup"
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: "Node: Run script"
        id: script
        run: node ./scripts/generateBuildData.mjs
      - name: 'Git: Send them back'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 🤖 Generate builddata.json
