name: 'Review dependencies'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v3
      - name: 'Review dependencies'
        uses: actions/dependency-review-action@v2
